# -*- coding: utf-8 -*-
"""Times New Roman 12D 327+334"""

"""
Diecase data:

diecaseID - workshop's unique name for this diecase,
typeface - fount name,
series - fount serial number,
size - type size (D if Didot, i.e. European),
setWidth - set width of this typeface in this size,
wedge - wedge/stopbar series for this typeface
"""

diecaseID = '327-12-KS01'
typeface = 'Times New Roman'
series = 327
size = '12D'
setWidth = 12
wedge = 'S5'

"""
Matrix case layout: 

It's a multi-dimensional array, where:
  -top level (dict) lists available styles,
  -middle level (dict) lists characters for each style,
  -bottom level (tuple) lists character's coordinates and unit value.
  
layout = {
           roman       : { char1 : (column, row, units),
                           char2 : (column, row, units),
                           etc. 
                          },
           bold        : {character definitions},
           italic      : {character definitions},
           smallcaps   : {character definitions},
           subscript   : {character definitions},
           superscript : {character definitions}
         }

  char - a character as found in input text (utf-8 encoded),
  column - column's 'number' (e.g. 'NL', 'A', 'O') - this will be addressed
        (any corrections based on caster's settings will be applied later,
         like changing D column to EF combination when using unit shift)
  row - row number (1...15, or 16 for HMN, KMN, unit-shift diecases),
  units - unit width of a character, optional.
  
If no unit value is given for char, use unit widths calculated 
from the row's unit width, based on the normal wedge's values.
If unit width is specified - compare it with row's unit width, calculate
the difference and then use D10/D11 wedges to add or subtract units.
We can also use unit-shift for casting a character from n-th row with
the (n-1)-th row's unit value; we must add D signal to the combination.

Exceptions to be caught:
-IndexError: tuple index out of range (no unit value given for char)
-KeyError: character is not found in style's layout (use roman instead)
-KeyError: style is not found in diecase (use roman instead, or stop
if roman is not found as well)
"""


def roman():
    pass
def bold():
    pass
def italic():
    pass
def smallcaps():
    pass
def subscript():
    pass
def superscript():
    pass


layout = {
          roman : {
                   'a' : ('H', 9, 7),
                   'ą' : ('K', 9, 7),
                   'b' : ('E', 11, 7),
                   'c' : ('I', 5, 7),
                   'ć' : ('J', 5, 7),
                   'd' : ('H', 10, 7),
                   'e' : ('G', 6, 7),
                   'ę' : ('K', 5, 7),
                   'f' : ('F', 3, 6),
                   'g' : ('F', 9, 7),
                   'h' : ('K', 10, 8),
                   'i' : ('H', 2, 5),
                   'j' : ('I', 2, 5),
                   'k' : ('L', 10, 8),
                   'l' : ('J', 2, 5),
                   'ł' : ('K', 2, 5),
                   'm' : ('G', 14, 15),
                   'n' : ('F', 10),
                   'ń' : ('N', 9),
                   'o' : ('B', 9),
                   'ó' : ('L', 9),
                   'p' : ('J', 10),
                   'q' : ('C', 10),
                   'r' : ('E', 4),
                   's' : ('F', 4),
                   'ś' : ('H', 4),
                   't' : ('L', 2),
                   'u' : ('G', 9),
                   'v' : ('E', 9),
                   'w' : ('N', 12),
                   'x' : ('J', 9),
                   'y' : ('I', 9),
                   'z' : ('H', 5),
                   'ź' : ('L', 5),
                   'ż' : ('M', 5),
                   'A' : ('G', 13),
                   'Ą' : ('L', 13),
                   'B' : ('H', 11),
                   'C' : ('K', 12),
                   'Ć' : ('NL', 12),
                   'D' : ('B', 14),
                   'E' : ('K', 11),
                   'Ę' : ('C', 12),
                   'F' : ('J', 12),
                   'G' : ('C', 14),
                   'H' : ('I', 14),
                   'I' : ('E', 3),
                   'J' : ('F', 5),
                   'K' : ('J', 14),
                   'L' : ('I', 12),
                   'Ł' : ('B', 10),
                   'M' : ('G', 15),
                   'N' : ('F', 14),
                   'Ń' : ('K', 14),
                   'O' : ('F', 13),
                   #'Ó' : (),
                   'P' : ('D', 10),
                   'Q' : ('J', 13),
                   'R' : ('E', 13),
                   'S' : ('B', 10),
                   'Ś' : ('NI', 9),
                   'T' : ('J', 11),
                   'U' : ('H', 14),
                   'V' : ('D', 12),
                   'W' : ('D', 15),
                   'X' : ('I', 13),
                   'Y' : ('H', 13),
                   'Z' : ('H', 12),
                   'Ź' : ('A', 12),
                   #'Ż' : (),
                   '1' : ('D', 6),
                   '2' : ('E', 6),
                   '3' : ('F', 6),
                   '4' : ('D', 7),
                   '5' : ('E', 7),
                   '6' : ('F', 7),
                   '7' : ('G', 7),
                   '8' : ('D', 8),
                   '9' : ('E', 8),
                   '0' : ('F', 8),
                   '+' : ('A', 16),
                   '×' : ('NL', 16),
                   '[' : ('NI', 1),
                   ']' : ('NL', 1),
                   '(' : ('A', 2),
                   ')' : ('B', 2),
                   ':' : ('C', 3),
                   ';' : ('D', 3),
                   '?' : ('N', 5),
                   '/' : ('NL', 4),
                   '°' : ('NI', 5),
                   '-' : ('E', 2),
                   #'–' : (),
                   #'—' : (),
                   '=' : ('H', 16),
                   '.' : ('M', 1),
                   '!' : ('B', 3),
                   '%' : ('E', 16),
                   '•' : ('O', 1),
                   '*' : ('G', 10),
                   #'„' : (),
                   #'”' : (),
                   ',' : ('L', 1),
                   "'" : ('F', 1),
                   '’' : ('E', 1)
                   },
           bold : {
                   'a' : ('G', 8),
                   'ą' : ('K', 6),
                   'b' : ('I', 6),
                   'c' : ('J', 4),
                   'ć' : ('L', 4),
                   'd' : ('H', 7),
                   'e' : ('I', 4),
                   'ę' : ('M', 4),
                   'f' : ('F', 2),
                   'g' : ('I', 7),
                   'h' : ('J', 8),
                   'i' : ('H', 1),
                   'j' : ('I', 1),
                   'k' : ('M', 9),
                   'l' : ('J', 1),
                   'ł' : ('K', 1),
                   'm' : ('D', 14),
                   'n' : ('C', 6),
                   'ń' : ('K', 7),
                   'o' : ('H', 8),
                   'ó' : ('K', 8),
                   'p' : ('J', 6),
                   'q' : ('L', 8),
                   'r' : ('I', 3),
                   's' : ('J', 3),
                   'ś' : ('K', 3),
                   't' : ('L', 3),
                   'u' : ('J', 7),
                   'v' : ('O', 5),
                   'w' : ('N', 11),
                   #'x' : (),
                   'y' : ('I', 8),
                   'z' : ('K', 4),
                   'ź' : ('N', 4),
                   'ż' : ('O', 4),
                   'A' : ('I', 16),
                   'Ą' : ('O', 13),
                   'B' : ('NL', 15),
                   'C' : ('NI', 12),
                   #'Ć' : (),
                   'D' : ('O', 14),
                   'E' : ('M', 11),
                   'Ę' : ('I', 10),
                   'F' : ('O', 10),
                   'G' : ('B', 16),
                   'H' : ('M', 14),
                   'I' : ('G', 3),
                   'J' : ('O', 9),
                   'K' : ('J', 15),
                   'L' : ('F', 12),
                   'Ł' : ('O', 11),
                   'M' : ('I', 15),
                   'N' : ('C', 16),
                   'Ń' : ('NL', 14),
                   'O' : ('L', 14),
                   'Ó' : ('NI', 14),
                   'P' : ('G', 12),
                   'Q' : ('N', 16),
                   'R' : ('H', 15),
                   'S' : ('M', 10),
                   'Ś' : ('NL', 9),
                   'T' : ('L', 11),
                   'U' : ('A', 15),
                   'V' : ('J', 16),
                   'W' : ('M', 15),
                   'X' : ('L', 15),
                   'Y' : ('M', 16),
                   'Z' : ('E', 15),
                   'Ź' : ('N', 15),
                   #'Ż' : (),
                   '1' : ('M', 6),
                   '2' : ('N', 6),
                   '3' : ('O', 6),
                   '4' : ('L', 7),
                   '5' : ('M', 7),
                   '6' : ('N', 7),
                   '7' : ('O', 7),
                   '8' : ('M', 8),
                   '9' : ('N', 8),
                   '0' : ('O', 8),
                   #'+' : (),
                   #'×' : (),
                   #'[' : (),
                   #']' : (),
                   '(' : ('N', 2),
                   ')' : ('O', 2),
                   ':' : ('M', 3),
                   ';' : ('D', 5),
                   '?' : ('L', 6),
                   #'/' : (),
                   #'°' : (),
                   '-' : ('M', 2),
                   #'–' : (),
                   #'—' : (),
                   #'=' : (),
                   '.' : ('NI', 2),
                   '!' : ('O', 3),
                   '%' : ('F', 16),
                   #'•' : (),
                   #'*' : (),
                   #'„' : (),
                   #'”' : (),
                   ',' : ('NL', 2),
                   "'" : ('N', 1),
                   '’' : ('NL', 2)
                   },
         italic : {
                   'a' : ('B', 8),
                   'ą' : ('NI', 7),
                   'b' : ('NL', 6),
                   'c' : ('C', 5),
                   'ć' : ('A', 5),
                   'd' : ('A', 6),
                   'e' : ('E', 5),
                   'ę' : ('A', 4),
                   'f' : ('C', 2),
                   'g' : ('B', 6),
                   'h' : ('A', 9),
                   'i' : ('D', 1),
                   'j' : ('C', 1),
                   'k' : ('N', 9),
                   'l' : ('B', 1),
                   'ł' : ('A', 1),
                   'm' : ('M', 13),
                   'n' : ('C', 5),
                   'ń' : ('N', 10),
                   'o' : ('NL', 5),
                   'ó' : ('NL', 7),
                   'p' : ('A', 7),
                   'q' : ('C', 8),
                   'r' : ('A', 3),
                   's' : ('C', 4),
                   'ś' : ('H', 3),
                   't' : ('D', 2),
                   'u' : ('A', 8),
                   'v' : ('B', 5),
                   'w' : ('G', 11),
                   'x' : ('C', 9),
                   'y' : ('B', 7),
                   'z' : ('B', 4),
                   'ź' : ('G', 4),
                   'ż' : ('D', 4),
                   'A' : ('E', 12),
                   #'Ą' : (),
                   'B' : ('B', 11),
                   'C' : ('L', 12),
                   #'Ć' : (),
                   'D' : ('D', 13),
                   'E' : ('F', 11),
                   'Ę' : ('K', 15),
                   'F' : ('NL', 10),
                   'G' : ('M', 12),
                   'H' : ('A', 14),
                   'I' : ('NL', 3),
                   'J' : ('C', 7),
                   'K' : ('B', 15),
                   'L' : ('D', 11),
                   'Ł' : ('I', 11),
                   'M' : ('F', 15),
                   'N' : ('B', 13),
                   #'Ń' : (),
                   'O' : ('C', 13),
                   #'Ó' : (),
                   'P' : ('C', 11),
                   'Q' : ('K', 16),
                   'R' : ('C', 15),
                   'S' : ('A', 10),
                   #'Ś' : (),
                   'T' : ('E', 11),
                   'U' : ('A', 13),
                   'V' : ('G', 16),
                   'W' : ('E', 14),
                   'X' : ('N', 13),
                   'Y' : ('O', 12),
                   'Z' : ('NI', 11),
                   #'Ź' : (),
                   'Ż' : ('NI', 16),
                   #'1' : (),
                   #'2' : (),
                   #'3' : (),
                   #'4' : (),
                   #'5' : (),
                   #'6' : (),
                   #'7' : (),
                   #'8' : (),
                   #'9' : (),
                   #'0' : (),
                   #'+' : (),
                   #'×' : (),
                   #'[' : (),
                   #']' : (),
                   #'(' : (),
                   #')' : (),
                   ':' : ('NI', 4),
                   ';' : ('N', 3),
                   '?' : ('NI', 6),
                   #'/' : (),
                   #'°' : (),
                   #'-' : (),
                   #'–' : (),
                   #'—' : (),
                   #'=' : (),
                   #'.' : (),
                   '!' : ('NI', 3),
                   #'%' : (),
                   #'•' : (),
                   #'*' : (),
                   #'„' : (),
                   #'”' : (),
                   #',' : (),
                   #"'" : (),
                   #'’' : ()
                   }
}

diecase = (diecaseID, typeface, series, size, wedge, setWidth, layout)