#! /bin/sh
### BEGIN INIT INFO
# Provides:          powerbuttond
# Required-Start:    $network sshd
# Required-Stop:     sendsigs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Power button daemon
# Description:       This lights the green LED after the interface is booted, and waits for the shutdown button to be pressed.
### END INIT INFO

# Author: Christophe Slychan

PATH=/usr/bin:/usr/sbin:/bin:/sbin
DESC=powerbuttondaemon
NAME=powerbuttond.py
DAEMON=/usr/bin/$NAME

. /lib/lsb/init-functions

do_start()
{
	start-stop-daemon --start --exec $DAEMON -b
}

do_stop()
{
	start-stop-daemon --stop --name $NAME

}


case "$1" in
  start)
	log_daemon_msg "Starting $DESC" "$NAME"
	do_start
	;;
  stop)
	log_daemon_msg "Stopping $DESC" "$NAME"
	do_stop
	;;
  restart)
	log_daemon_msg "Restarting $DESC" "$NAME"
	do_stop
	do_start
	;;
esac

:
