"""add outside characters, unit arrangements, ribbon table

Revision ID: 92dc72589add
Revises: 
Create Date: 2017-03-01 20:35:15.643665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92dc72589add'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ribbons',
    sa.Column('ribbon_id', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('customer', sa.Text(), nullable=True),
    sa.Column('diecase_id', sa.Text(), nullable=True),
    sa.Column('wedge_name', sa.Text(), nullable=False),
    sa.Column('contents', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['diecase_id'], ['matrix_cases.diecase_id'], ),
    sa.PrimaryKeyConstraint('ribbon_id')
    )
    op.add_column('matrix_cases', sa.Column('unit_arrangements', sa.Text(), nullable=True))
    op.alter_column('matrix_cases', 'wedge', new_column_name='wedge_name',
                    existing_type=sa.Text(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matrix_cases', 'wedge_name', new_column_name='wedge',
               existing_type=sa.Text(), nullable=True)
    op.drop_column('matrix_cases', 'unit_arrangements')
    # ### end Alembic commands ###
